name: dataset-processor
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python>=3.10
  - pytorch>=2.4.0
  - pytorch-cuda>=12.4
  - torchvision>=0.8
  - torchaudio
  - tqdm
  - pandas
  - matplotlib
  - pip
  - pycocotools>=2
  - ultralytics
  - pip:
    - exif